### ISSUE TITLE
[Bug] Episode indicator numbers on some TV show widgets

### ISSUE THREAD

**Issue by tjamieg** [jurialmunkey/plugin.video.themoviedb.helper#61]
Episode indicator numbers are showing on some TV show widgets even when every Trakt API subsetting is turned off, as shown below:

Noticed this on both Windows and Android installations.

Am I right in thinking the indicator is supposed to count "unwatched" episodes too, not watched ones?

![Settings](https://user-images.githubusercontent.com/48328397/73142318-255e8180-4085-11ea-98de-b5366b18aeda.jpg)
![Trending Now](https://user-images.githubusercontent.com/48328397/73142320-25f71800-4085-11ea-855f-b81d24025db2.jpg)
![Watch It Again](https://user-images.githubusercontent.com/48328397/73142321-25f71800-4085-11ea-9796-c4917f7b7b42.jpg)

Also, separate issue but related to the image above - the "TV Shows > Your Recently Watched" list in TMDb Helper only shows a few entries. My guess is that it queries Trakt for 10 episodes (or 20 depending on setting), but then groups these episodes into shows.

**Comment by jurialmunkey** [comment]
Yeah, I've noticed this bug. 

Do you have merge local db details setting enabled?

**Comment by tjamieg** [comment]
By that, do you mean "Get additional details from the local Kodi library database"? If so, then no I don't have that enabled. I don't have any local library stuff set up whatsoever... purely just using add-on data.

**Comment by jurialmunkey** [comment]
@tjamieg - Thanks - just useful info for test cases.

Watched episode counts should be fixed now in v2.2.42 - Please test and confirm.

**Comment by jurialmunkey** [comment]
How "Your Recently Watched" is meant to work is it looks at last 200 episodes watched in last 6 months and finds 10 tvshows... but it does seem that there is a bug here

**Comment by tjamieg** [comment]
> Watched episode counts should be fixed now in v2.2.42 - Please test and confirm.
> Also, should now only show unwatched counts on tvshows where you have watched at least one episode.

I can confirm that the watched indicators and counts seem to be working perfectly in v2.2.42.
You make it look so easy... brilliant work, thank you!

**Comment by jurialmunkey** [comment]
@tjamieg - Excellent thanks for testing and confirming. I'm fairly certain I've now fixed the "Your Recently Watched" bug too. Can you test again with latest (v.2.2.43) and confirm?

**Comment by tjamieg** [comment]
"Your Recently Watched" now shows the correct amount of tv shows.

But the "Based on Your Recently Watched" and "Your In Progress" widgets are now failing to load and bringing up errors...

```
2020-01-27 00:27:11.681 T:14132   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'tuple' object has no attribute 'tmdb_id'
                                            Traceback (most recent call last):
                                              File "C:\Users\gwill\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\plugin.py", line 11, in <module>
                                                Container().router()
                                              File "C:\Users\gwill\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\container.py", line 841, in router
                                                self.list_becauseyouwatched()
                                              File "C:\Users\gwill\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\container.py", line 580, in list_becauseyouwatched
                                                recentitems = func(userslug, self.params.get('type'), limit=5, islistitem=False)
                                              File "C:\Users\gwill\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\traktapi.py", line 252, in get_recentlywatched
                                                return self.get_limitedlist(history, tmdbtype, limit, islistitem)
                                              File "C:\Users\gwill\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\traktapi.py", line 220, in get_limitedlist
                                                if item.tmdb_id and item.tmdb_id not in added_items:
                                            AttributeError: 'tuple' object has no attribute 'tmdb_id'
                                            -->End of Python script error report<--
2020-01-27 00:27:11.815 T:6396   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.themoviedb.helper/?info=trakt_becauseyouwatched&widget=True&type=tv&reload=
2020-01-27 00:27:11.815 T:15200   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'tuple' object has no attribute 'tmdb_id'
                                            Traceback (most recent call last):
                                              File "C:\Users\gwill\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\plugin.py", line 11, in <module>
                                                Container().router()
                                              File "C:\Users\gwill\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\container.py", line 848, in router
                                                self.list_trakthistory()
                                              File "C:\Users\gwill\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\container.py", line 450, in list_trakthistory
                                                items = traktapi.get_inprogress(userslug, limit=self.trakt_limit)
                                              File "C:\Users\gwill\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\traktapi.py", line 268, in get_inprogress
                                                for i in self.get_recentlywatched_shows(userslug, islistitem=False):
                                              File "C:\Users\gwill\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\traktapi.py", line 247, in get_recentlywatched_shows
                                                return self.get_limitedlist(history, 'tv', limit, islistitem)
                                              File "C:\Users\gwill\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\traktapi.py", line 220, in get_limitedlist
                                                if item.tmdb_id and item.tmdb_id not in added_items:
                                            AttributeError: 'tuple' object has no attribute 'tmdb_id'
                                            -->End of Python script error report<--
2020-01-27 00:27:11.940 T:9020   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.themoviedb.helper/?info=trakt_inprogress&widget=True&type=tv&reload=
2020-01-27 00:27:16.510 T:15368   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'tuple' object has no attribute 'tmdb_id'
                                            Traceback (most recent call last):
                                              File "C:\Users\gwill\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\plugin.py", line 11, in <module>
                                                Container().router()
                                              File "C:\Users\gwill\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\container.py", line 841, in router
                                                self.list_becauseyouwatched()
                                              File "C:\Users\gwill\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\container.py", line 580, in list_becauseyouwatched
                                                recentitems = func(userslug, self.params.get('type'), limit=5, islistitem=False)
                                              File "C:\Users\gwill\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\traktapi.py", line 252, in get_recentlywatched
                                                return self.get_limitedlist(history, tmdbtype, limit, islistitem)
                                              File "C:\Users\gwill\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\traktapi.py", line 220, in get_limitedlist
                                                if item.tmdb_id and item.tmdb_id not in added_items:
                                            AttributeError: 'tuple' object has no attribute 'tmdb_id'
                                            -->End of Python script error report<--
2020-01-27 00:27:16.633 T:9020   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.themoviedb.helper/?info=trakt_becauseyouwatched&widget=True&type=movie&reload=
2020-01-27 00:27:20.965 T:6764  NOTICE: [plugin.video.themoviedb.helper]
                                            HTTP Error Code: 404
                                            Request: http://webservice.fanart.tv/v3/tv/373328?api_key=fcca59bee130b70db37ee43e63f8d6c1&client_key=9a0b810189f012d9186a56f3f3535516
```

Also noticed these in the log but they seemed unrelated:
```
2020-01-27 00:25:37.819 T:15760  NOTICE: [plugin.video.themoviedb.helper]
                                            HTTP Error Code: 500
                                            Request: http://webservice.fanart.tv/v3/tv/259866?api_key=fcca59bee130b70db37ee43e63f8d6c1&client_key=9a0b810189f012d9186a56f3f3535516
2020-01-27 00:25:38.199 T:15760  NOTICE: [plugin.video.themoviedb.helper]
                                            HTTP Error Code: 500
                                            Request: http://webservice.fanart.tv/v3/tv/260338?api_key=fcca59bee130b70db37ee43e63f8d6c1&client_key=9a0b810189f012d9186a56f3f3535516
2020-01-27 00:25:39.624 T:15760  NOTICE: [plugin.video.themoviedb.helper]
                                            HTTP Error Code: 500
                                            Request: http://webservice.fanart.tv/v3/tv/281617?api_key=fcca59bee130b70db37ee43e63f8d6c1&client_key=9a0b810189f012d9186a56f3f3535516
2020-01-27 00:25:51.989 T:15760  NOTICE: [plugin.video.themoviedb.helper]
                                            HTTP Error Code: 500
                                            Request: http://webservice.fanart.tv/v3/tv/328092?api_key=fcca59bee130b70db37ee43e63f8d6c1&client_key=9a0b810189f012d9186a56f3f3535516
2020-01-27 00:25:53.190 T:15760  NOTICE: [plugin.video.themoviedb.helper]
                                            HTTP Error Code: 500
                                            Request: http://webservice.fanart.tv/v3/tv/281620?api_key=fcca59bee130b70db37ee43e63f8d6c1&client_key=9a0b810189f012d9186a56f3f3535516
2020-01-27 00:25:54.176 T:11232  NOTICE: [plugin.video.themoviedb.helper]
                                            HTTP Error Code: 500
                                            Request: http://webservice.fanart.tv/v3/tv/311876?api_key=fcca59bee130b70db37ee43e63f8d6c1&client_key=9a0b810189f012d9186a56f3f3535516
2020-01-27 00:26:01.239 T:15760  NOTICE: [plugin.video.themoviedb.helper]
                                            HTTP Error Code: 500
                                            Request: http://webservice.fanart.tv/v3/tv/258744?api_key=fcca59bee130b70db37ee43e63f8d6c1&client_key=9a0b810189f012d9186a56f3f3535516
2020-01-27 00:26:22.428 T:15760  NOTICE: [plugin.video.themoviedb.helper]
                                            ConnectionError: HTTPConnectionPool(host='webservice.fanart.tv', port=80): Max retries exceeded with url: /v3/tv/279536?api_key=fcca59bee130b70db37ee43e63f8d6c1&client_key=9a0b810189f012d9186a56f3f3535516 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020A0D7C1F98>: Failed to establish a new connection: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))
2020-01-27 00:26:22.704 T:15760  NOTICE: [plugin.video.themoviedb.helper]
                                            HTTP Error Code: 500
                                            Request: http://webservice.fanart.tv/v3/tv/269641?api_key=fcca59bee130b70db37ee43e63f8d6c1&client_key=9a0b810189f012d9186a56f3f3535516
2020-01-27 00:26:47.178 T:4584  NOTICE: [plugin.video.themoviedb.helper]
                                            HTTP Error Code: 504
                                            Request: http://webservice.fanart.tv/v3/tv/328552?api_key=fcca59bee130b70db37ee43e63f8d6c1&client_key=9a0b810189f012d9186a56f3f3535516
2020-01-27 00:26:54.716 T:11232  NOTICE: [plugin.video.themoviedb.helper]
                                            HTTP Error Code: 504
                                            Request: http://webservice.fanart.tv/v3/tv/348204?api_key=fcca59bee130b70db37ee43e63f8d6c1&client_key=9a0b810189f012d9186a56f3f3535516
```

**Comment by jurialmunkey** [comment]
@tjamieg - Okay should be fixed now.

RE: HTTP Error Code: 500 / 504 - fanart.tv API service appears to be down currently, hence the errors.

**Comment by tjamieg** [comment]
Yep, all good this end. I think this issue can be closed now. Thanks again!

**Comment by jurialmunkey** [comment]
Excellent! Thanks for the bug report and testing the changes 😁
